import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.List;

import repositories.IRepository;
import repositories.impl.UserRepository;
import domain.User;


public class Main {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
		String url="jdbc:hsqldb:hsql://localhost/workdb";
		User akowalski = new User();
		akowalski.setLogin("s12305");
		akowalski.setPassword("1234qwer");
		
		try {
			
			Connection connection = DriverManager.getConnection(url);
			/*
			String createTableSql = 
					"CREATE TABLE users("
					+ "id int GENERATED BY DEFAULT AS IDENTITY,"
					+ "login VARCHAR(20),"
					+ "password VARCHAR(20)"
					+ ")";
			Statement createTable = connection.createStatement();
			createTable.executeUpdate(createTableSql);
			*/
		IRepository<User> users = new UserRepository(connection);
			users.save(akowalski);
			List<User> usersFromDb= users.getAll();
			
			for(User userFromDb: usersFromDb)
				System.out.println(userFromDb.getId()+" "+userFromDb.getLogin()+" "+userFromDb.getPassword());
			
			User u = users.get(2);
			u.setPassword("1234qwer");
			users.update(u);
			users.delete(usersFromDb.get(0));
			
			for(User userFromDb: users.getAll())
				System.out.println(userFromDb.getId()+" "+userFromDb.getLogin()+" "+userFromDb.getPassword());
			
			
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
		System.out.println("end");
	}

}
